### Core Copier config

# Require Copier v9 or newer
_min_copier_version: "9.10.0"

# Use a custom answers file name at the project root
_answers_file: ".python-project-foundry.answers.yaml"

# Only render from the template/ subtree
_subdirectory: "template"

# Use .jinja as the suffix for Jinja-templated files
_templates_suffix: ".jinja"

# Preserve final newlines and fail immediately if a template references a
# question that has not been defined.
_envops:
  keep_trailing_newline: true
  undefined: "jinja2.StrictUndefined"

# Keep links as links if symlinks are added to the template in the future.
_preserve_symlinks: true
